version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/flutter/arqma_wallet_gui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"

  - package-ecosystem: "pub"
    directory: "/flutter-mobile/arqma_wallet_mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"

  - package-ecosystem: "pub"
    directory: "/flutter-android/arqma_wallet_android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
