name: Arqma Electron Wallet Build

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Patch node gyp (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: npm install -g node-gyp

      - name: Install dependencies
        run: npm i --force
        env:
          npm_config_registry: https://registry.npmjs.org/
          npm_config_fetch_retries: 5
          npm_config_fetch_retry_mintimeout: 20000
          npm_config_fetch_retry_maxtimeout: 120000

      - name: Download Arqma binaries
        run: node ./build/download-binaries.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARQMA_REPO_TOKEN: ${{ secrets.ARQMA_REPO_TOKEN }}

      - name: Display
        run: echo "$RUNNER_OS"

      - name: Extract binaries
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -xvf ${{ github.workspace }}/downloads/latest.gz --directory ${{ github.workspace }}
          ls ${{ github.workspace }}/bin

      - name: Extract Windows binaries
        if: matrix.os == 'windows-latest'
        run: |
          mkdir ${{ github.workspace }}\bin
          tar -xvf ${{ github.workspace }}\downloads\latest.zip -C ${{ github.workspace }}\bin
          dir ${{ github.workspace }}\bin

      - name: Extract macOS binaries
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p bin
          unzip -o downloads/latest.zip -d bin
          ls -la bin

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: npm run build-mac-arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Linux binaries
        if: matrix.os == 'ubuntu-latest'
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB }}

      - name: Publish Windows binaries
        if: matrix.os == 'windows-latest'
        run: npm run build-windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB }}

  #    - name: Remove un-needed Windows artifacts
  #      if: matrix.os == 'windows-latest'
  #      run: |
  #        ls
        #   rm -r -fo win-unpacked
  #      working-directory: .\dist\electron\Packaged

      - name: Remove un-needed Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        run: rm -rf ./*/
        working-directory: ./dist/electron/Packaged


#      - name: Upload artifacts Windows
#        if: matrix.os == 'windows-latest'
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ runner.os }}
#          path: ${{ github.workspace }}\dist\electron\Packaged

#      - name: Upload artifacts Ubuntu 22.04 self hosted
#        if: matrix.os == 'ubuntu22204-ex'
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ matrix.os }}
#          path: ${{ github.workspace }}/dist/electron/Packaged

#     - name: copy file via ssh password
#        if: matrix.os == 'ubuntu-latest'
#       uses: appleboy/scp-action@v0.1.7
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.SSH_USER }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         port: ${{ secrets.PORT }}
#         source: ./dist/electron/Packaged/*
#         target: downloads/GUI/
#         strip_components: 3

#     - name: Copy folder content recursively to remote Windows
#       if: matrix.os == 'windows-latest'
#       uses: garygrossgarten/github-action-scp@release
#       with:
#         local: ${{ github.workspace }}\dist\electron\Packaged\
#         remote: downloads/GUI/
#         strip_components: 3
#         concurrency: 4
#         host: ${{ secrets.HOST }}
#         port: ${{ secrets.PORT }}
#         username: ${{ secrets.SSH_USER }}
#         privateKey: ${{ secrets.PRIVATE_KEY}}
